name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint with ruff
        run: |
          poetry run ruff check .

      - name: Type check with mypy
        run: |
          poetry run mypy .

      - name: Run tests with pytest
        run: |
          poetry run pytest --cov=datadoc --cov-report=term-missing
